"""empty message

Revision ID: 32854e35888d
Revises: a5cffa318ac2
Create Date: 2025-12-04 00:29:34.941477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32854e35888d'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follower')
    # ### end Alembic commands ###
