"""empty message

Revision ID: f0ef1a01cf0e
Revises: 8148fa496fe2
Create Date: 2025-12-04 02:17:01.366535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ef1a01cf0e'
down_revision = '8148fa496fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_comment_text_key', type_='unique')

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint('media_type_key', type_='unique')
        batch_op.drop_constraint('media_url_key', type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_email_key', ['email'])

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_unique_constraint('media_url_key', ['url'])
        batch_op.create_unique_constraint('media_type_key', ['type'])

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_unique_constraint('comment_comment_text_key', ['comment_text'])

    # ### end Alembic commands ###
